---
- name: extract paperless-ng
  unarchive:
    src: "https://github.com/paperless-ngx/paperless-ngx/releases/download/ngx-{{ paperlessng_version }}/paperless-ngx-{{ paperlessng_version }}.tar.xz"
    remote_src: yes
    dest: "{{ tempdir.path }}"
